const fs = require('fs');

const ORG = 'codeijoe';
const LABEL = 'mission-completed';

// DAFTAR MISI AKTIF
const MISSIONS = [
  { id: 'protocol-zero', title: 'Protocol Zero' },
  { id: 'protocol-one',  title: 'Protocol One' },
  { id: 'protocol-two',  title: 'Protocol Two' }
];

async function fetchWinners(repoId) {
  console.log(`📡 Scanning Sector: ${repoId}...`);
  
  const query = `repo:${ORG}/${repoId} is:pr is:closed label:${LABEL}`;
  const url = `https://api.github.com/search/issues?q=${encodeURIComponent(query)}&sort=updated&order=desc`;

  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Codeijoe-Leaderboard',
        'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`
      }
    });

    if (!response.ok) {
        console.warn(`⚠️ Skipped ${repoId}: API Error ${response.status}`);
        return [];
    }
    
    const data = await response.json();
    return (data.items || []).map(pr => ({ ...pr, missionId: repoId })); 

  } catch (error) {
    console.error(`❌ Error scanning ${repoId}:`, error);
    return [];
  }
}

function generateHTML(allWinners) {
  let tableContent = '';

  if (allWinners.length === 0) {
      tableContent = `<tr><td colspan="4" class="p-8 text-center text-gray-500 font-mono">No verified engineers yet.</td></tr>`;
  } else {
      // Sort berdasarkan waktu kelulusan (terbaru di atas)
      allWinners.sort((a, b) => new Date(b.closed_at) - new Date(a.closed_at));

      tableContent = allWinners.map((pr) => {
        const user = pr.user;
        const date = new Date(pr.closed_at).toLocaleDateString();
        const missionTitle = MISSIONS.find(m => m.id === pr.missionId)?.title || pr.missionId;
        
        return `
          <tr class="hover:bg-gray-800 transition-colors border-b border-gray-700">
            <td class="p-4 flex items-center gap-3">
              <img src="${user.avatar_url}" class="w-10 h-10 rounded-full border border-gray-600">
              <div class="flex flex-col">
                <a href="${user.html_url}" class="text-green-400 font-bold hover:underline font-mono" target="_blank">
                    @${user.login}
                </a>
              </div>
            </td>
            
            <td class="p-4 text-gray-300 font-mono">
              <span class="bg-gray-700 px-2 py-1 rounded text-xs border border-gray-600">
                ${missionTitle}
              </span>
            </td>
            
            <td class="p-4 text-gray-500 text-sm font-mono">${date}</td>
            
            <td class="p-4 text-right">
              <a href="${pr.html_url}" target="_blank" class="text-blue-400 text-xs border border-blue-400 px-2 py-1 rounded hover:bg-blue-400 hover:text-white transition">
                PROOF
              </a>
            </td>
          </tr>
        `;
      }).join('');
  }

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Codeijoe Hall of Fame</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>body { background-color: #0d1117; color: #c9d1d9; }</style>
</head>
<body class="p-6 md:p-12 max-w-5xl mx-auto">
    <header class="mb-12 text-center">
        <h1 class="text-4xl font-bold mb-2 tracking-tighter text-white">CODEIJOE<span class="text-green-500">™</span> HALL OF FAME</h1>
        <p class="text-gray-500 font-mono text-sm">WHERE AI ENDS, ENGINEERING BEGINS.</p>
    </header>
    <div class="border border-gray-700 rounded-lg overflow-hidden bg-[#161b22] shadow-2xl">
        <table class="w-full text-left border-collapse">
            <thead class="bg-gray-800 text-xs uppercase text-gray-400">
                <tr>
                    <th class="p-4 font-mono">Engineer</th>
                    <th class="p-4 font-mono">Mission Cleared</th>
                    <th class="p-4 font-mono">Verified At</th>
                    <th class="p-4 text-right font-mono">Evidence</th>
                </tr>
            </thead>
            <tbody>
                ${tableContent}
            </tbody>
        </table>
    </div>
    <footer class="mt-12 text-center text-xs text-gray-600 font-mono">
        Generated by Codeijoe Automation • Est. 2024
    </footer>
</body>
</html>`;
}

async function main() {
  console.log(`🚀 Starting Multi-Sector Scan...`);
  const promises = MISSIONS.map(m => fetchWinners(m.id));
  const results = await Promise.all(promises);
  const allWinners = results.flat();
  
  console.log(`✅ Total Verified Engineers: ${allWinners.length}`);
  const html = generateHTML(allWinners);
  fs.writeFileSync('index.html', html);
  console.log('📄 index.html updated.');
}

main();
