const fs = require('fs');

// Konfigurasi Target
const ORG = 'codeijoe';
const REPO = 'protocol-zero';
const LABEL = 'mission-completed';

async function fetchWinners() {
  console.log('📡 Scanning for Engineers...');
  
  // Menggunakan GitHub Search API untuk mencari PR yang merged/closed dengan label khusus
  // Query: repo:codeijoe/protocol-zero is:pr is:closed label:mission-completed
  const query = `repo:${ORG}/${REPO} is:pr is:closed label:${LABEL}`;
  const url = `https://api.github.com/search/issues?q=${encodeURIComponent(query)}&sort=updated&order=desc`;

  try {
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Codeijoe-Leaderboard',
        // Token opsional untuk rate limit lebih tinggi (diinject via GitHub Actions)
        'Authorization': `Bearer ${process.env.GITHUB_TOKEN}` 
      }
    });

    if (!response.ok) throw new Error(`API Error: ${response.status}`);
    
    const data = await response.json();
    return data.items; // Array of PRs
  } catch (error) {
    console.error('❌ Failed to fetch winners:', error);
    process.exit(1);
  }
}

function generateHTML(winners) {
  const winnerRows = winners.map((pr, index) => {
    const user = pr.user;
    const date = new Date(pr.closed_at).toLocaleDateString();
    
    // Template baris tabel per pemenang
    return `
      <tr class="hover:bg-gray-800 transition-colors border-b border-gray-700">
        <td class="p-4 text-gray-400 font-mono">#${winners.length - index}</td>
        <td class="p-4 flex items-center gap-3">
          <img src="${user.avatar_url}" class="w-10 h-10 rounded-full border border-gray-600">
          <a href="${user.html_url}" class="text-green-400 font-bold hover:underline font-mono" target="_blank">
            @${user.login}
          </a>
        </td>
        <td class="p-4 text-gray-300 font-mono">Protocol Zero</td>
        <td class="p-4 text-gray-500 text-sm font-mono">${date}</td>
        <td class="p-4 text-right">
          <a href="${pr.html_url}" target="_blank" class="text-blue-400 text-xs border border-blue-400 px-2 py-1 rounded hover:bg-blue-400 hover:text-white transition">
            PROOF
          </a>
        </td>
      </tr>
    `;
  }).join('');

  // Template HTML Utuh (Minimalist Dark Mode)
  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Codeijoe Hall of Fame</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background-color: #0d1117; color: #c9d1d9; }
        .glow { text-shadow: 0 0 10px rgba(74, 222, 128, 0.5); }
    </style>
</head>
<body class="p-6 md:p-12 max-w-5xl mx-auto">
    <header class="mb-12 text-center">
        <h1 class="text-4xl font-bold mb-2 tracking-tighter text-white">CODEIJOE<span class="text-green-500">™</span> HALL OF FAME</h1>
        <p class="text-gray-500 font-mono text-sm">WHERE AI ENDS, ENGINEERING BEGINS.</p>
    </header>

    <div class="border border-gray-700 rounded-lg overflow-hidden bg-[#161b22] shadow-2xl">
        <table class="w-full text-left border-collapse">
            <thead class="bg-gray-800 text-xs uppercase text-gray-400">
                <tr>
                    <th class="p-4 font-mono">Rank</th>
                    <th class="p-4 font-mono">Engineer</th>
                    <th class="p-4 font-mono">Mission</th>
                    <th class="p-4 font-mono">Verified At</th>
                    <th class="p-4 text-right font-mono">Evidence</th>
                </tr>
            </thead>
            <tbody>
                ${winnerRows}
            </tbody>
        </table>
    </div>

    <footer class="mt-12 text-center text-xs text-gray-600 font-mono">
        Generated by Codeijoe Automation • Est. 2024
    </footer>
</body>
</html>
  `;
}

async function main() {
  const winners = await fetchWinners();
  console.log(`✅ Found ${winners.length} verified engineers.`);
  
  const html = generateHTML(winners);
  
  // Tulis ke file index.html
  fs.writeFileSync('index.html', html);
  console.log('📄 index.html generated successfully.');
}

main();